[tool.poetry]
name = "whisper-tools"
version = "0.1.0"
description = ""
authors = ["Jag Srawan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.7"
requests = "^2.32.3"
faster-whisper = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
